import { PlantType } from './types';

// L-System rules:
// F = draw forward, + = turn right, - = turn left
// [ = push state, ] = pop state
// X = variable (replaced by rule)

export const PLANT_TYPES: PlantType[] = [
  {
    id: 'cherry_tree',
    name: 'Cherry Blossom',
    nameKo: '벚나무',
    category: 'tree',
    growthTime: 120,
    waterNeed: 0.3,
    baseColor: { h: 340, s: 70, l: 75 },
    colorVariants: [
      { h: 340, s: 70, l: 75 },
      { h: 350, s: 60, l: 80 },
      { h: 330, s: 80, l: 70 },
    ],
    lSystemRule: 'FF-[-F+F+F]+[+F-F-F]',
    lSystemAngle: 22,
    lSystemIterations: 4,
    maxHeight: 140,
    description: 'A graceful tree with delicate pink blossoms',
    rarity: 'uncommon',
    seasonBonus: 'spring',
    aestheticValue: 15,
  },
  {
    id: 'oak_tree',
    name: 'Oak Tree',
    nameKo: '참나무',
    category: 'tree',
    growthTime: 180,
    waterNeed: 0.2,
    baseColor: { h: 120, s: 50, l: 35 },
    colorVariants: [
      { h: 120, s: 50, l: 35 },
      { h: 130, s: 45, l: 40 },
      { h: 110, s: 55, l: 30 },
    ],
    lSystemRule: 'FF+[+F-F-F]-[-F+F+F]',
    lSystemAngle: 25,
    lSystemIterations: 4,
    maxHeight: 160,
    description: 'A strong, majestic oak with dense foliage',
    rarity: 'common',
    seasonBonus: 'summer',
    aestheticValue: 12,
  },
  {
    id: 'rose',
    name: 'Rose',
    nameKo: '장미',
    category: 'flower',
    growthTime: 60,
    waterNeed: 0.6,
    baseColor: { h: 0, s: 80, l: 50 },
    colorVariants: [
      { h: 0, s: 80, l: 50 },
      { h: 330, s: 70, l: 60 },
      { h: 15, s: 90, l: 55 },
      { h: 50, s: 80, l: 70 },
    ],
    lSystemRule: 'F[+F]F[-F]F',
    lSystemAngle: 25,
    lSystemIterations: 3,
    maxHeight: 60,
    description: 'A classic rose with layered petals',
    rarity: 'common',
    seasonBonus: 'summer',
    aestheticValue: 10,
  },
  {
    id: 'sunflower',
    name: 'Sunflower',
    nameKo: '해바라기',
    category: 'flower',
    growthTime: 80,
    waterNeed: 0.5,
    baseColor: { h: 45, s: 90, l: 55 },
    colorVariants: [
      { h: 45, s: 90, l: 55 },
      { h: 40, s: 85, l: 60 },
      { h: 50, s: 95, l: 50 },
    ],
    lSystemRule: 'F[+F]F[-F]+F',
    lSystemAngle: 15,
    lSystemIterations: 3,
    maxHeight: 90,
    description: 'A tall, cheerful sunflower',
    rarity: 'common',
    seasonBonus: 'summer',
    aestheticValue: 8,
  },
  {
    id: 'lavender',
    name: 'Lavender',
    nameKo: '라벤더',
    category: 'flower',
    growthTime: 70,
    waterNeed: 0.3,
    baseColor: { h: 270, s: 50, l: 65 },
    colorVariants: [
      { h: 270, s: 50, l: 65 },
      { h: 280, s: 45, l: 70 },
      { h: 260, s: 55, l: 60 },
    ],
    lSystemRule: 'FF[+F][-F]F[+F]',
    lSystemAngle: 10,
    lSystemIterations: 3,
    maxHeight: 55,
    description: 'Fragrant purple stalks swaying gently',
    rarity: 'common',
    seasonBonus: 'spring',
    aestheticValue: 9,
  },
  {
    id: 'maple_tree',
    name: 'Maple Tree',
    nameKo: '단풍나무',
    category: 'tree',
    growthTime: 150,
    waterNeed: 0.25,
    baseColor: { h: 15, s: 80, l: 50 },
    colorVariants: [
      { h: 15, s: 80, l: 50 },
      { h: 30, s: 85, l: 55 },
      { h: 0, s: 75, l: 45 },
    ],
    lSystemRule: 'F[+FF][-FF]F[+F][-F]',
    lSystemAngle: 28,
    lSystemIterations: 3,
    maxHeight: 150,
    description: 'A beautiful tree with vibrant autumn colors',
    rarity: 'uncommon',
    seasonBonus: 'autumn',
    aestheticValue: 14,
  },
  {
    id: 'mushroom_red',
    name: 'Fly Agaric',
    nameKo: '광대버섯',
    category: 'mushroom',
    growthTime: 40,
    waterNeed: 0.7,
    baseColor: { h: 0, s: 85, l: 45 },
    colorVariants: [
      { h: 0, s: 85, l: 45 },
      { h: 10, s: 80, l: 50 },
      { h: 350, s: 90, l: 40 },
    ],
    lSystemRule: 'F',
    lSystemAngle: 0,
    lSystemIterations: 1,
    maxHeight: 40,
    description: 'A charming red mushroom with white spots',
    rarity: 'uncommon',
    seasonBonus: 'autumn',
    aestheticValue: 7,
  },
  {
    id: 'mushroom_glow',
    name: 'Glowing Mushroom',
    nameKo: '빛나는 버섯',
    category: 'mushroom',
    growthTime: 50,
    waterNeed: 0.8,
    baseColor: { h: 180, s: 70, l: 60 },
    colorVariants: [
      { h: 180, s: 70, l: 60 },
      { h: 160, s: 65, l: 55 },
      { h: 200, s: 75, l: 65 },
    ],
    lSystemRule: 'F',
    lSystemAngle: 0,
    lSystemIterations: 1,
    maxHeight: 35,
    description: 'A mystical mushroom that glows softly at night',
    rarity: 'rare',
    seasonBonus: null,
    aestheticValue: 12,
  },
  {
    id: 'fern',
    name: 'Forest Fern',
    nameKo: '고사리',
    category: 'bush',
    growthTime: 55,
    waterNeed: 0.5,
    baseColor: { h: 140, s: 60, l: 40 },
    colorVariants: [
      { h: 140, s: 60, l: 40 },
      { h: 150, s: 55, l: 45 },
      { h: 130, s: 65, l: 35 },
    ],
    lSystemRule: 'F[-F][+F]F[-F]+F',
    lSystemAngle: 30,
    lSystemIterations: 4,
    maxHeight: 55,
    description: 'Elegant fern fronds unfurling gracefully',
    rarity: 'common',
    seasonBonus: 'spring',
    aestheticValue: 8,
  },
  {
    id: 'wisteria',
    name: 'Wisteria',
    nameKo: '등나무',
    category: 'vine',
    growthTime: 100,
    waterNeed: 0.4,
    baseColor: { h: 270, s: 60, l: 70 },
    colorVariants: [
      { h: 270, s: 60, l: 70 },
      { h: 280, s: 55, l: 75 },
      { h: 300, s: 50, l: 72 },
    ],
    lSystemRule: 'F[+F][-F]FF[+F][-F]',
    lSystemAngle: 20,
    lSystemIterations: 3,
    maxHeight: 110,
    description: 'Cascading purple blossoms on twisting vines',
    rarity: 'rare',
    seasonBonus: 'spring',
    aestheticValue: 18,
  },
  {
    id: 'bamboo',
    name: 'Bamboo',
    nameKo: '대나무',
    category: 'grass',
    growthTime: 45,
    waterNeed: 0.4,
    baseColor: { h: 100, s: 50, l: 45 },
    colorVariants: [
      { h: 100, s: 50, l: 45 },
      { h: 110, s: 45, l: 50 },
      { h: 90, s: 55, l: 40 },
    ],
    lSystemRule: 'FF[+F]FF[-F]F',
    lSystemAngle: 8,
    lSystemIterations: 3,
    maxHeight: 120,
    description: 'Tall, elegant bamboo that sways in the wind',
    rarity: 'common',
    seasonBonus: 'summer',
    aestheticValue: 10,
  },
  {
    id: 'lotus',
    name: 'Sacred Lotus',
    nameKo: '연꽃',
    category: 'flower',
    growthTime: 90,
    waterNeed: 0.9,
    baseColor: { h: 330, s: 60, l: 80 },
    colorVariants: [
      { h: 330, s: 60, l: 80 },
      { h: 0, s: 0, l: 95 },
      { h: 300, s: 50, l: 75 },
    ],
    lSystemRule: 'F[+F][-F]',
    lSystemAngle: 30,
    lSystemIterations: 2,
    maxHeight: 45,
    description: 'A serene lotus floating on still water',
    rarity: 'legendary',
    seasonBonus: 'summer',
    aestheticValue: 20,
  },
];

export function getPlantType(id: string): PlantType | undefined {
  return PLANT_TYPES.find(p => p.id === id);
}
